name: siven_app
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publication

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  dropdown_search: ^5.0.3
  provider: ^6.0.0
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_charts: ^20.1.59
  #syncfusion_flutter_maps: ^20.1.59
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  collection: ^1.15.0
  shared_preferences: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^4.0.0
  geojson: ^1.0.0
  pdf: ^3.8.1
  path_provider: ^2.0.11
  open_filex: ^3.2.1
  location: ^5.0.0
  url_launcher: ^6.1.10
  table_calendar: ^3.0.8
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.3.2
  build_runner: ^2.3.3
  sqflite_common_ffi: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/Isotipo-.webp"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/ministerio_de_salud_nicaragua_2020.webp
    - lib/assets/Roboto-Regular.ttf
    - lib/assets/SIVEN-SD.webp
    - lib/assets/SIVEN-SD.webp
    - lib/assets/Isotipo-.webp
    - lib/assets/homeicon/icono-registro.webp
    - lib/assets/homeicon/alerta-_1_-2.webp
    - lib/assets/homeicon/equipo-medico-_4_-1.webp
    - lib/assets/homeicon/estudio-1.webp
    - lib/assets/homeicon/configuracion-2.webp
    - lib/assets/homeicon/analitica-1.webp
    - lib/assets/homeicon/clinica.webp
    - lib/assets/homeicon/usuario.webp
    - lib/assets/homeicon/siven.webp
    - lib/assets/GeoJson/Boaco.geojson
    - lib/assets/GeoJson/Carazo.geojson
    - lib/assets/GeoJson/Chinandega.geojson
    - lib/assets/GeoJson/Chontales.geojson
    - lib/assets/GeoJson/Estelí.geojson
    - lib/assets/GeoJson/Granada.geojson
    - lib/assets/GeoJson/Jinotega.geojson
    - lib/assets/GeoJson/León.geojson
    - lib/assets/GeoJson/Madriz.geojson
    - lib/assets/GeoJson/Managua.geojson
    - lib/assets/GeoJson/Masaya.geojson
    - lib/assets/GeoJson/Matagalpa.geojson
    - lib/assets/GeoJson/Nueva_Segovia.geojson
    - lib/assets/GeoJson/Región_Autónoma_de_la_Costa_Caribe_Norte.geojson
    - lib/assets/GeoJson/Región_Autónoma_de_la_Costa_Caribe_Sur.geojson
    - lib/assets/GeoJson/Río_San_Juan.geojson
    - lib/assets/GeoJson/Rivas.geojson
    - lib/assets/GeoJson/ni.json
